services:

  trellis-app:
    restart: unless-stopped
    extends:
      file: trellis.yml
      service: trellis-dev
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./config/fastdds-config.xml:/fastdds-config.xml
      - ./config/cyclone-dds.xml:/cyclone-dds.xml
      - ./config/trellis-ros.yaml:/root/trellis_ws/install/trellis_ros/share/trellis_ros/config/config.yaml
      - ./scripts:/root/trellis_ws/scripts
      - $HOME/trellis/models:/models
      - $HOME/trellis/torch:/root/.cache/torch
      - synthesis:/synthesis
    command: bash -c "cd /opt/TRELLIS && python app.py"

volumes:
  synthesis:
    driver: local
